bot:
  automerge: true
travis:
  secure:
    BINSTAR_TOKEN: VabNUhSSNL9wreGqE1JpBJyBt2o3MRVonBDZRMvFxtHuCPobLB2gRTVKA7cF/2CixfzwxpZHqzyZQ0zbTo60FtyELuqjmjxO48aBt50BrdgTm0ulNZGTWArWS829Tpj1bLsLJMZNcsPk8s9mYM8paE0/qfTD3o/RmStePUBOcJCry4sWOF1Flo0GmB8AiWLcB2VDiq3n9fMcfPLErr2b+k485KsWLLw4bxfTiFjei058jDC8uggDa6Pk3OApzYviVH7abHgSTCcHo5oCXOjws6Br6YSRGdPbNot8q91QD1xexrL1ZFpPGF7Bt+l39/49h/jHeo2hWeeGzjXkpCLYdLLCYCnEROdxqc/5Pz4kf5D0oaEiaqm9eluUG0rTmLxu2/XEadyx59ySw1EqRRuAQsJKpCOMdg4CrG0vQZxomm1wM3d1Pmf80nDcWTYzbJGmzTooWJAm+CbgKH/95HndZqQG1JAMuyW4S+nxAIJiTeRN73RBCQnvQ3j5Vi6MB1MlfEtOLcHUsUJqS61yJXjz2adhpMlMD/W+kigrTb2A72nmk2uoWyTeyuRGL59qi3aw1Zab1SwQ3gV+RjvzM6OyD/6oBAhQA1P+aB3KeOOcxVzZGXz8g2v546sU1+KgXjqC5LITjnShPa//g8M8H9A/pmcptE10MYbeTEARLfOWQNI=
conda_forge_output_validation: true
